export const APP_STRINGS = {
  app: {
    name: 'SportsCarnival',
    loginTagline: 'Manage your events',
    registerTagline: 'Join the competition',
  },
  auth: {
    welcomeBack: 'Welcome Back',
    signInSubtitle: 'Sign in to continue to your account',
    createAccount: 'Create Account',
    signUpSubtitle: 'Get started with your sports journey',
    resetPassword: 'Reset Password',
    createNewPasswordTagline: 'Create a new password for your account',
  },
  buttons: {
    createAccount: 'Create Account',
    signIn: 'Sign In',
    updatePassword: 'Update Password',
    forgotPassword: 'Forgot Password?',
    signUp: 'Sign Up',
  },
  labels: {
    email: 'Email',
    name: 'Name',
    newPassword: 'New Password',
    password: 'Password',
    confirmPassword: 'Confirm New Password',
  },
  footer: {
    noAccount: "Don't have an account?",
    accountAlready: 'Already have an account?',
  },
  placeHolders: {
    email: 'Enter your email',
    password: 'Enter your password',
    fullName: 'Enter your full name',
    createPassword: 'Create a password',
    newPassword: 'Enter new password',
    confirmNewPassword: 'Confirm New Password',
    format: 'Format (Singles / Doubles)',
    teamName: 'Enter team name',
    captainName: 'Enter captain name',
    maxPlayers: 'Enter max players',
    playerName: 'Player Name',
    gender: 'Gender',
    prizeForFirst: 'Enter prize for first position',
    prizeForSecond: 'Enter prize for second position',
    prizeForThird: 'Enter prize for third position',
    rules: 'Enter rules separated by comma',
  },
  roleSelection: {
    chooseRole: 'Choose your role',
    heading: 'How will you participate?',
    subHeading:
      'Select your role to customize your experience. You can change this later in the settings.',
  },
  adminScreens: {
    greeting: 'Hello, Admin! 👋',
    totalEvents: 'Total Events',
    activeUsers: 'Active Users',
    team: 'Teams',
    matchesToday: 'Matches Today',
    quickActions: 'Quick Actions',
    addEvent: 'Add Event',
    addUser: 'Add User',
    settings: 'Settings',
    liveMatches: 'Live Matches',
  },
  organizerScreens: {
    greeting: 'Hello, Organizer! 👋',
    myEvents: 'My Events',
    pendingApprovals: 'Pending\nApprovals',
    teamsRegistered: 'Teams\nRegistered',
    liveMatches: 'Live Matches',
    createEvent: 'Create Event',
    reviewTeams: 'Review Teams',
    upcomingMatches: 'Upcoming Matches',
  },
  participantScreens: {
    greeting: 'Hello, Participant! 👋',
    myEvents: 'My Events',
    myTeam: 'My Team',
    matchesPlayed: 'Matches\nPlayed',
    wins: 'Wins',
    captain: 'Captain',
  },
  eventScreen: {
    eventManage: 'Tap an event to manage',
    editEvent: 'Edit Event',
    deleteEvent: 'Delete Event',
    createEvent: 'Create Event',
    all: 'All',
    live: 'Live',
    open: 'Open',
    upcoming: 'Upcoming',
    eventName: 'Event Name',
    sportName: 'Sport Name',
    format: 'Format',
    date: 'Date',
    time: 'Time',
    venue: 'Venue',
    totalTeams: 'Total Teams',
    deleteEventConfirmation: 'Are you sure you want to delete event?',
    saveChanges: 'Save Changes',
    allEvents: 'All Events',
    myEvents: 'My Events',
    teams: 'Teams',
    noEventFound: 'No Event Found',
    teamsRegistered: ' Teams Registered',
    edit: 'Edit',
    register: 'Register',
    delete: 'Delete',
    vs: 'VS',
    registrationOpen: 'Registration Open',
    winRate: 'Win Rate',
    todaysMatches: "Today's Matches",
    noTeamsFound: 'No Teams Found',
    createTeam: 'Create Team',
    editTeam: 'Edit Team',
    teamName: 'Team Name',
    captainName: 'Captain Name',
    selectSport: 'Select Sport',
    maxPlayers: 'Max Players',
    registerForEvent: 'Register for Event',
    selectFormat: 'Select Format',
    noDescription: 'No description available.',
    rulesSharedSoon: 'Rules will be shared soon.',
    description: 'Description',
    rulesAndRegulations: 'Rules & Regulations',
    teamNotCreated: 'Teams not created yet',
    fixtureNotCreated: 'Fixtures not created yet',
    createFixtures: 'Create Fixtures',
    prizeNotAnnounced: 'No prizes announced yet.',
    position: 'Position',
    reward: 'Reward',
    standardRules: 'Standard tournament rules apply',
    registrationClosed: 'Registration Closed',
    createTeamFirst: 'Please create teams first.',
    prizeForFirst: 'Prize for first position',
    prizeForSecond: 'Prize for second position',
    prizeForThird: 'Prize for third position',
    eventCompleted: 'Event Completed',
    fixturesReady: 'Fixtures Ready',
    teamsCreated: 'Teams Created',
    final: 'Final',
    semiFinal: 'Semi-Final',
    quarterFinal: 'Quarter-Final',
    notEnoughCompletedMatches: 'Not Enough Completed Matches',
    noEnoughRegistrations: 'No Enough Registrations',
    eventFull: 'Event Full',
    noMoreSlots: 'No more slots available',
    registered: 'Registered',
    registrationSuccessfull: 'You have registered successfully',
    noTeamsRequired:
      'No teams required for Singles format. Players will compete individually.',
    notEnoughSameGenderParticipants: 'Not enough same-gender participants',
    notEnoughSameGenderPairs: 'Not enough same-gender pairs',
    startMatch: 'Start Match',
    updateScore: 'Update Score',
    saveScore: 'Save Score',
    completeMatch: 'Complete Match',
    differentScores: 'Scores must be different to complete the match',
    noRegisteredParticipants: 'No participants registered',
    categories: 'Categories',
    prizes: 'Prizes',
    selectFormats: 'Select Format(s)',
    chooseFormat: 'Choose the format(s) you want to participate in',
  },
};
