export const APP_STRINGS = {
  app: {
    name: 'SportsCarnival',
    loginTagline: 'Manage your events',
    registerTagline: 'Join the competition',
  },
  auth: {
    welcomeBack: 'Welcome Back',
    signInSubtitle: 'Sign in to continue to your account',
    createAccount: 'Create Account',
    signUpSubtitle: 'Get started with your sports journey',
    resetPassword: 'Reset Password',
    createNewPasswordTagline: 'Create a new password for your account',
  },
  buttons: {
    createAccount: 'Create Account',
    signIn: 'Sign In',
    updatePassword: 'Update Password',
    forgotPassword: 'Forgot Password?',
    signUp: 'Sign Up',
  },
  labels: {
    email: 'Email',
    name: 'Full Name',
    newPassword: 'New Password',
    password: 'Password',
    confirmPassword: 'Confirm New Password',
  },
  footer: {
    noAccount: "Don't have an account?",
    accountAlready: 'Already have an account?',
  },
  placeHolders: {
    email: 'Enter your email',
    password: 'Enter your password',
    fullName: 'Enter your full name',
    createPassword: 'Create a password',
    newPassword: 'Enter new password',
    confirmNewPassword: 'Confirm New Password',
  },
  roleSelection: {
    chooseRole: 'Choose your role',
    heading: 'How will you participate?',
    subHeading:
      'Select your role to customize your experience. You can change this later in the settings.',
  },
  adminScreens: {
    heading: 'Admin Dashboard',
    greeting: 'Hello, User! 👋',
    totalEvents: 'Total Events',
    activeUsers: 'Active Users',
    team: 'Teams',
    matchesToday: 'Matches Today',
    quickActions: 'Quick Actions',
    addEvent: 'Add Event',
    addUser: 'Add User',
    settings: 'Settings',
    liveMatches: 'Live Matches',
  },
  organizerScreens: {
    heading: 'Organizer Dashboard',
    greeting: 'Hello, User! 👋',
    myEvents: 'My Events',
    pendingApprovals: 'Pending\nApprovals',
    teamsRegistered: 'Teams\nRegistered',
    liveMatches: 'Live Matches',
    createEvent: 'Create Event',
    reviewTeams: 'Review Teams',
    upcomingMatches: 'Upcoming Matches',
  },
  participantScreens: {
    heading: 'Participant Dashboard',
    greeting: 'Hello, User! 👋',
    myEvents: 'My Events',
    myTeam: 'My Team',
    matchesPlayed: 'Matches\nPlayed',
    wins: 'Wins',
    captain: 'Captain',
  },
  eventScreen: {
    eventManage: 'Tap an event to manage',
    editEvent: 'Edit Event',
    deleteEvent: 'Delete Event',
    all: 'All',
    live: 'Live',
    open: 'Open',
    upcoming: 'Upcoming',
    eventName: 'Event Name',
    sportName: 'Sport Name',
    format: 'Format',
    date: 'Date',
    time: 'Time',
    venue: 'Venue',
    totalTeams: 'Total Teams',
    deleteEventConfirmation: 'Are you sure you want to delete event?',
  },
};
