import { Event } from '../models/Event';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    name: 'Inter College Badminton',
    sport: 'Badminton',
    format: '2v2',
    date: '24 Jan 2026',
    time: '10:00 AM',
    venue: 'Court A',
    status: 'UPCOMING',
    registeredTeams: 8,
    totalTeams: 12,
  },
  {
    id: '2',
    name: 'Table Tennis Finals',
    sport: 'Table Tennis',
    format: '1v1',
    date: '21 Jan 2026',
    time: '05:00 PM',
    venue: 'Hall 2',
    status: 'LIVE',
    registeredTeams: 6,
    totalTeams: 6,
  },
  {
    id: '3',
    name: 'Carrom Championship',
    sport: 'Carrom',
    format: '1v1',
    date: '20 Jan 2026',
    time: '03:00 PM',
    venue: 'Room 4',
    status: 'COMPLETED',
    registeredTeams: 10,
    totalTeams: 10,
  },
  {
    id: '4',
    name: 'Pool Finals',
    sport: 'Pool',
    format: '1v1',
    date: '20 Jan 2026',
    time: '03:00 PM',
    venue: 'Room 4',
    status: 'OPEN',
    registeredTeams: 2,
    totalTeams: 5,
  },
  {
    id: '5',
    name: 'Foosball Tournament',
    sport: 'Foosball',
    format: '2v2',
    date: '20 Jan 2026',
    time: '03:00 PM',
    venue: 'Room 4',
    status: 'UPCOMING',
    registeredTeams: 10,
    totalTeams: 12,
  },
  {
    id: '6',
    name: 'Carrom Championship',
    sport: 'Carrom',
    format: '1v1',
    date: '20 Jan 2026',
    time: '03:00 PM',
    venue: 'Room 4',
    status: 'OPEN',
    registeredTeams: 3,
    totalTeams: 6,
  },
];
