import { Event } from '../models/Event';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    name: 'Inter College Badminton',
    sport: 'Badminton',
    format: '2v2',
    date: '24 Jan 2026',
    time: '10:00 AM',
    venue: 'Court A',
    status: 'OPEN',
    registeredTeams: 12,
    totalTeams: 12,
    registrationDeadline: '23 Jan 2026',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Inter college badminton tournament.',
    rules: ['Knockout format', 'Each match best of 3'],
    prizes: ['₹5000', 'Trophy'],
  },
  {
    id: '2',
    name: 'Table Tennis Finals',
    sport: 'Table Tennis',
    format: '1v1',
    date: '21 Jan 2026',
    time: '05:00 PM',
    venue: 'Hall 2',
    status: 'LIVE',
    registeredTeams: 6,
    totalTeams: 6,
    registrationDeadline: '20 Jan 2026',
    teamsCreated: true,
    fixturesCreated: true,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'TT finals tournament.',
    rules: ['Single elimination'],
    prizes: ['₹3000'],
  },
  {
    id: '3',
    name: 'Carrom Championship',
    sport: 'Carrom',
    format: '1v1',
    date: '20 Jan 2026',
    time: '03:00 PM',
    venue: 'Room 4',
    status: 'COMPLETED',
    registeredTeams: 10,
    totalTeams: 10,
    registrationDeadline: '19 Jan 2026',
    teamsCreated: true,
    fixturesCreated: true,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Carrom championship.',
    rules: ['League + finals'],
    prizes: ['₹2000'],
  },
  {
    id: '4',
    name: 'Pool Finals',
    sport: 'Pool',
    format: '1v1',
    date: '20 Jan 2026',
    time: '03:00 PM',
    venue: 'Room 4',
    status: 'OPEN',
    registeredTeams: 5,
    totalTeams: 5,
    registrationDeadline: '19 Jan 2026',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Pool tournament.',
    rules: ['Straight knockout'],
    prizes: ['₹1500'],
  },
  {
    id: '5',
    name: 'Foosball Tournament',
    sport: 'Foosball',
    format: '2v2',
    date: '20 Jan 2026',
    time: '03:00 PM',
    venue: 'Room 4',
    status: 'UPCOMING',
    registeredTeams: 10,
    totalTeams: 12,
    registrationDeadline: '19 Jan 2026',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Foosball fun event.',
    rules: ['Group stage'],
    prizes: ['₹2500'],
  },
  {
    id: '6',
    name: 'Chess Open',
    sport: 'Chess',
    format: '1v1',
    date: '26 Jan 2026',
    time: '11:00 AM',
    venue: 'Hall 1',
    status: 'OPEN',
    registeredTeams: 4,
    totalTeams: 16,
    registrationDeadline: '25 Jan 2026',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Open chess tournament.',
    rules: ['Swiss system'],
    prizes: ['₹4000'],
  },
  {
    id: '7',
    name: 'Volleyball Cup',
    sport: 'Volleyball',
    format: '2v2',
    date: '27 Jan 2026',
    time: '02:00 PM',
    venue: 'Ground',
    status: 'UPCOMING',
    registeredTeams: 3,
    totalTeams: 12,
    registrationDeadline: '26 Jan 2026',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Volleyball tournament.',
    rules: ['Knockout'],
    prizes: ['₹7000'],
  },
  {
    id: '8',
    name: 'Basketball 3v3',
    sport: 'Basketball',
    format: '2v2',
    date: '28 Jan 2026',
    time: '04:00 PM',
    venue: 'Court B',
    status: 'OPEN',
    registeredTeams: 6,
    totalTeams: 8,
    registrationDeadline: '27 Jan 2026',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: '3v3 basketball.',
    rules: ['Group + knockout'],
    prizes: ['₹6000'],
  },
  {
    id: '9',
    name: 'Cricket League',
    sport: 'Cricket',
    format: '2v2',
    date: '30 Jan 2026',
    time: '09:00 AM',
    venue: 'Stadium',
    status: 'UPCOMING',
    registeredTeams: 5,
    totalTeams: 10,
    registrationDeadline: '29 Jan 2026',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Cricket league.',
    rules: ['League format'],
    prizes: ['₹10000'],
  },
  {
    id: '10',
    name: 'Badminton Singles',
    sport: 'Badminton',
    format: '1v1',
    date: '31 Jan 2026',
    time: '01:00 PM',
    venue: 'Court C',
    status: 'OPEN',
    registeredTeams: 1,
    totalTeams: 8,
    registrationDeadline: '30 Jan 2026',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Singles badminton.',
    rules: ['Knockout'],
    prizes: ['₹3000'],
  },
];
