import { Team } from '../models/Team';

export const mockTeams: Team[] = [
  {
    id: '1',
    name: 'Thunder Hawks',
    captain: 'John Doe',
    currentPlayers: 15,
    totalPlayers: 15,
    sport: 'FOOSBALL',
    wins: 5,
    losses: 2,
  },
  {
    id: '2',
    name: 'Storm Riders',
    captain: 'Jane Smith',
    currentPlayers: 10,
    totalPlayers: 12,
    sport: 'POOL',
    wins: 3,
    losses: 4,
  },
  {
    id: '3',
    name: 'Crimson Warriors',
    captain: 'Amit Sharma',
    currentPlayers: 11,
    totalPlayers: 15,
    sport: 'BADMINTON',
    wins: 6,
    losses: 1,
  },
  {
    id: '4',
    name: 'Golden Eagles',
    captain: 'Rahul Mehta',
    currentPlayers: 8,
    totalPlayers: 12,
    sport: 'TABLE TENNIS',
    wins: 2,
    losses: 5,
  },
  {
    id: '5',
    name: 'Blue Sharks',
    captain: 'Neha Verma',
    currentPlayers: 14,
    totalPlayers: 15,
    sport: 'CARROM',
    wins: 7,
    losses: 3,
  },
  {
    id: '6',
    name: 'Iron Titans',
    captain: 'Kunal Singh',
    currentPlayers: 15,
    totalPlayers: 15,
    sport: 'POOL',
    wins: 9,
    losses: 1,
  },
  {
    id: '7',
    name: 'Sky Strikers',
    captain: 'Pooja Nair',
    currentPlayers: 9,
    totalPlayers: 12,
    sport: 'FOOSBALL',
    wins: 4,
    losses: 2,
  },
  {
    id: '8',
    name: 'Shadow Panthers',
    captain: 'Rohit Khanna',
    currentPlayers: 12,
    totalPlayers: 15,
    sport: 'BADMINTON',
    wins: 3,
    losses: 6,
  },
  {
    id: '9',
    name: 'Rapid Foxes',
    captain: 'Anjali Gupta',
    currentPlayers: 7,
    totalPlayers: 12,
    sport: 'POOL',
    wins: 1,
    losses: 5,
  },
  {
    id: '10',
    name: 'Royal Challengers',
    captain: 'Suresh Iyer',
    currentPlayers: 15,
    totalPlayers: 15,
    sport: 'TABLE TENNIS',
    wins: 8,
    losses: 2,
  },
  {
    id: '11',
    name: 'Net Smashers',
    captain: 'Varun Patel',
    currentPlayers: 10,
    totalPlayers: 12,
    sport: 'CARROM',
    wins: 5,
    losses: 3,
  },
  {
    id: '12',
    name: 'Desert Falcons',
    captain: 'Mohammed Ali',
    currentPlayers: 13,
    totalPlayers: 15,
    sport: 'FOOSBALL',
    wins: 6,
    losses: 4,
  },
];
