import { Event } from '../models/Event';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    name: 'Inter College Badminton',
    sport: 'Badminton',
    formats: ['Singles', 'Doubles'],
    date: '2026-01-24',
    time: '10:00',
    venue: 'Court A',
    status: 'OPEN',
    registeredTeams: 0,
    totalTeams: 12,
    registrationDeadline: '2026-01-23',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Inter college badminton tournament with singles and doubles.',
    rules: ['Knockout format', 'Each match best of 3'],
    prizes: ['₹5000', 'Trophy', '₹2000'],
  },
  {
    id: '2',
    name: 'Table Tennis Finals',
    sport: 'Table Tennis',
    formats: ['Singles'],
    date: '2026-01-21',
    time: '17:00',
    venue: 'Hall 2',
    status: 'UPCOMING',
    registeredTeams: 0,
    totalTeams: 6,
    registrationDeadline: '2026-01-20',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'TT finals tournament.',
    rules: ['Single elimination'],
    prizes: ['₹3000'],
  },
  {
    id: '3',
    name: 'Carrom Championship',
    sport: 'Carrom',
    formats: ['Singles', 'Doubles'],
    date: '2026-01-20',
    time: '15:00',
    venue: 'Room 4',
    status: 'COMPLETED',
    registeredTeams: 0,
    totalTeams: 10,
    registrationDeadline: '2026-01-19',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Carrom championship.',
    rules: ['League + finals'],
    prizes: ['₹2000'],
  },
  {
    id: '4',
    name: 'Pool Finals',
    sport: 'Pool',
    formats: ['Singles'],
    date: '2026-01-20',
    time: '15:00',
    venue: 'Room 4',
    status: 'OPEN',
    registeredTeams: 0,
    totalTeams: 5,
    registrationDeadline: '2026-01-19',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Pool tournament.',
    rules: ['Straight knockout'],
    prizes: ['₹1500'],
  },
  {
    id: '5',
    name: 'Foosball Tournament',
    sport: 'Foosball',
    formats: ['Doubles'],
    date: '2026-01-20',
    time: '15:00',
    venue: 'Room 4',
    status: 'UPCOMING',
    registeredTeams: 0,
    totalTeams: 12,
    registrationDeadline: '2026-01-19',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Foosball fun event.',
    rules: ['Group stage'],
    prizes: ['₹2500'],
  },
  {
    id: '6',
    name: 'Chess Open',
    sport: 'Chess',
    formats: ['Singles'],
    date: '2026-01-26',
    time: '11:00',
    venue: 'Hall 1',
    status: 'OPEN',
    registeredTeams: 0,
    totalTeams: 16,
    registrationDeadline: '2026-01-25',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Open chess tournament.',
    rules: ['Swiss system'],
    prizes: ['₹4000'],
  },
  {
    id: '7',
    name: 'Foosball Cup',
    sport: 'Foosball',
    formats: ['Doubles'],
    date: '2026-01-27',
    time: '14:00',
    venue: 'Ground',
    status: 'UPCOMING',
    registeredTeams: 0,
    totalTeams: 12,
    registrationDeadline: '2026-01-26',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Foosball tournament.',
    rules: ['Knockout'],
    prizes: ['₹7000'],
  },
  {
    id: '8',
    name: 'Chess Blitz',
    sport: 'Chess',
    formats: ['Singles'],
    date: '2026-01-28',
    time: '16:00',
    venue: 'Court B',
    status: 'OPEN',
    registeredTeams: 0,
    totalTeams: 8,
    registrationDeadline: '2026-01-27',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: '1v1 chess blitz.',
    rules: ['Group + knockout'],
    prizes: ['₹6000'],
  },
  {
    id: '9',
    name: 'Pool League',
    sport: 'Pool',
    formats: ['Singles', 'Doubles'],
    date: '2026-01-30',
    time: '09:00',
    venue: 'Stadium',
    status: 'UPCOMING',
    registeredTeams: 0,
    totalTeams: 10,
    registrationDeadline: '2026-01-29',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Pool league with singles and doubles.',
    rules: ['League format'],
    prizes: ['₹10000'],
  },
  {
    id: '10',
    name: 'Badminton Singles',
    sport: 'Badminton',
    formats: ['Singles'],
    date: '2026-01-31',
    time: '13:00',
    venue: 'Court C',
    status: 'OPEN',
    registeredTeams: 0,
    totalTeams: 8,
    registrationDeadline: '2026-01-30',
    teamsCreated: false,
    fixturesCreated: false,
    teams: [],
    fixtures: [],
    registrations: [],
    description: 'Singles badminton.',
    rules: ['Knockout'],
    prizes: ['₹3000'],
  },
];
